Laser quantum
Ulm-IQO/qudi-iqo-modules pull request #16
Opened 2022-03-09 12:09 UTC by takuya-ulm

## Description

- Bug fix
- Introduce VISA class and Command class

## Motivation and Context

- Some bugs were found in transition to the new core
- Even though the visa package was used in several laser hardware, it was not encapsulated

## How Has This Been Tested?

- Tested with gem laser with smd 6000 psu 

## Types of changes

-  Bug fix
- ~~New feature~~
- ~~Breaking change (Causes existing functionality to not work as expected)~~

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] I have documented my changes in `/docs/changelog.md`.
- [ ] My change requires additional/updated documentation.
- [x ] I have updated the documentation accordingly.
- [x ] I have added/updated the config example for any module docstrings as necessary.
- [x ] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

2022-11-27 17:10 UTC, LukePiewalker requested changes
Was testing it with an SMD6000 and found some things which need some adjustment. However we should also test with the other PSU Types if we have some at hand?

2022-11-27 17:10 UTC, LukePiewalker commented on src/qudi/hardware/laser/laserquantum_laser.py
> +        return self.cmd.get_lcd_status()
Here I get an attribute error with the SMD6000. Is this command necessary? Since its not specified in the interface? What abour using get_extra_info?

2022-11-27 17:10 UTC, LukePiewalker commented on src/qudi/hardware/laser/laserquantum_laser.py
> +        return
cmd.sys_info for me just gives
System_info(firmware_ver='', psu_time='', laser_time='', laser_over_1A_time='') so there is not really much to take from it I guess?

Why json.dumps(...)? Maybe it was inteded to be returned?

2022-11-27 17:10 UTC, LukePiewalker commented on docs/changelog.md
> +None
We should merge main again into this branch to get the changelog up to date.

2022-12-12 09:36 UTC, takuya-ulm commented on src/qudi/hardware/laser/laserquantum_laser.py
> +        return self.cmd.get_lcd_status()
'STATUSLCD' is not implemented, which gives what is written in the display. This is now modified such that it gives empty strings if the device does not have this comman.

2022-12-12 09:39 UTC, takuya-ulm commented on src/qudi/hardware/laser/laserquantum_laser.py
> +        return
Now simoly str is used to convert the dictionary type to the string type. 
It is strange that nothing is obtained at your device. At least, it should give information which is implemented on your PSU. I will double check them.

2022-12-13 16:59 UTC, takuya-ulm commented on src/qudi/hardware/laser/laserquantum_laser.py
> +        return
The problem on no ouput from get_extra_info is also fixed now.

2022-12-14 09:51 UTC, takuya-ulm commented on docs/changelog.md
> +None
Main is merged into this branch and the changelog is updated.

2024-08-15 18:36 UTC, TobiasSpohn commented on src/qudi/hardware/laser/laserquantum_laser.py
> +        return self.cmd.get_lcd_status()
Tested it with SMD6000, works.

2024-08-15 18:37 UTC, TobiasSpohn commented on src/qudi/hardware/laser/laserquantum_laser.py
> +        return
Tested it with SMD6000, works.

2024-08-15 18:39 UTC, TobiasSpohn commented on docs/changelog.md
> +None
Merged main again and updated changelog

2024-08-15 18:45 UTC, TobiasSpohn commented
This pull looks good from my side. I tested it with SMD6000 for now and it works well.
I made some slight changes:

- fixed default config
- on activation the current power and current setpoint will be set to the current power and current of the device, not just 0
- in the logic, I removed the automatic query loop start upon activation as it is not needed, when only controlling the hardware with it. The GUI will automatically start the query loop upon activation.

2024-08-19 10:47 UTC, TobiasSpohn approved these changes
Thanks Takuya, pull request looks good and was tested by me with SMD6000 and SMD12 PSUs.

2024-08-19 10:48 UTC, TobiasSpohn approved these changes
Changes have been addressed.

2024-08-19 11:43 UTC, merged