New scanning toolchain
Ulm-IQO/qudi-iqo-modules pull request #18
Opened 2022-06-13 09:17 UTC by timoML

The maintenance team is introducing the new scanning toolchain that is designed to be fully configurable with respect to multiple signal inputs (eg. APD counts, analogue inputs) and an arbitrary scanning axes configuration. To this end, its written in a very modular way. 

In order to enable the community to start testing and to adapt code that is relying on the scanning (/confocal) toolchain, we're planning to merge this first, reasonably stable version.
Please see the [project page](https://github.com/orgs/Ulm-IQO/projects/8) for ongoing development and feel free to report bugs there, in this PR, or via the [issues](https://github.com/Ulm-IQO/qudi-iqo-modules/issues) feature.

## How Has This Been Tested?
A lot of dummy testing. Real hw tests are ongoing.

## Types of changes
- [ ] Bug fix
- [x] New feature
- [x] Breaking change (Causes existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] I have documented my changes in `/docs/changelog.md`.
- [x] My change requires additional/updated documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated the config example for any module docstrings as necessary.
- [x] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [x] All changed Jupyter notebooks have been stripped of their output cells.

2022-07-08 12:17 UTC, Neverhorst requested changes
- As discussed I think the config directory should not exist anymore (delete testing configs and move default.cfg to src/qudi/)
- History backward/forward is not working properly anymore.
- I'm getting weird Qt warnings about not being able to move an QObject to a target thread when deactivating the scanning logics and then trying to load the GUI again. Does not happen with other modules, e.g. time series.
- Encountered signal disconnect errors when deactivating the scanning toolchain. Pushed a possible fix but needs checking.

More review to follow...

2022-07-08 15:58 UTC, timoML commented
Can you reproducibly make the history not work anymore? I saw it a few times now, but mostly it works on my dummy and setup.

2022-07-09 20:54 UTC, Neverhorst commented
> Can you reproducibly make the history not work anymore? I saw it a few times now, but mostly it works on my dummy and setup. I think it could be related to the restored scan data marker (/position) being out of range...

- Load default.cfg
- clear all scanning related appdata
- load scanning gui
- start and finish X-Y scan
- start and finish X scan
- use zoom tool to select smaller X-Y scan area
- start and finish X-Y scan
- try to get backwards in history to get first X-Y scan... nothing happens (no errors, just no reaction)

2022-07-11 16:18 UTC, Neverhorst approved these changes

2022-07-12 13:32 UTC, merged