fix: not-fulfilled switch interface
Ulm-IQO/qudi-iqo-modules pull request #9
Opened 2022-01-26 15:01 UTC by timoML

PulseBlaster was broken before due to not fulfilled SwitchInterface.
Fixed with dummy implemntations.

## How Has This Been Tested?
On real setup (M26/4219)

## Screenshots (only if appropriate, delete if not):

## Types of changes
- [x] Bug fix
- [ ] New feature
- [ ] Breaking change (Causes existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] I have documented my changes in `/docs/changelog.md`.
- [ ] My change requires additional/updated documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated the config example for any module docstrings as necessary.
- [x] I have checked that the change does not contain obvious errors
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [x] All changed Jupyter notebooks have been stripped of their output cells.

2022-01-26 19:57 UTC, kay-jahnke requested changes
In my opinion, either the hardware implements the interface (it inherits the interface class) or it does not implement it and therefore also does not inherit it. It therefore does not make sense to pretend to implement it and then raise.

Hence I would suggest either to really implement the switch interface or completely drop it from the inheritance.

2022-01-27 08:11 UTC, timoML commented
I agree. Since I don't know anyone using the SwitchInterface, I went for the latter.

2022-01-27 08:18 UTC, kay-jahnke commented
A valid decision. 
But the import is still in there, plus the methods for the old switch interface (line 176ff and 1090ff). please kill all of it, as it is non-functional.

Have you tested that the rest still works?

2022-01-27 11:14 UTC, timoML commented
Ok, I didn't see those other methods. I used them to implement in the SwitchInterface now.
Basic tests with simple TTL sequences from the pulsed gui were done on Ilia's  setup after getting the file to run again.
He will continue to work with it; so maybe it's worth waiting for his feedback before merging...

2022-02-21 12:10 UTC, Neverhorst approved these changes

2022-02-21 13:52 UTC, kay-jahnke approved these changes
can't test it on hardware, but the code looks much better now.

2022-02-21 14:00 UTC, merged